import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// aplica 'dark' antes da hidratação para evitar flash
const setInitialTheme = `
(function () {
  try {
    const key = 'autentika-theme';
    const stored = localStorage.getItem(key);
    if (stored === 'dark') { document.documentElement.classList.add('dark'); return; }
    if (stored === 'light') { document.documentElement.classList.remove('dark'); return; }
    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      document.documentElement.classList.add('dark');
    }
  } catch {}
})();
`;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          storageKey="wlgcaptal-theme"
      >
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
